# Generated by Django 2.0 on 2018-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterstorage',
            name='remark',
            field=models.CharField(max_length=50),
        ),
    ]
