# Generated by Django 2.0 on 2018-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20180510_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterstorage',
            old_name='crate_at',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
