# Generated by Django 2.0.3 on 2018-05-16 23:49

from django.db import migrations, models
import django.db.models.deletion
import meat.utils.mixin


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20180516_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=(models.Model, meat.utils.mixin.DictMixin),
        ),
        migrations.RenameField(
            model_name='outstorage',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='enterstorage',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AddField(
            model_name='outstorage',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Customer'),
        ),
    ]
