# Generated by Django 2.0 on 2018-05-17 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meat.utils.mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_auto_20180516_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('hand_user', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, meat.utils.mixin.DictMixin),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Product')),
            ],
            bases=(models.Model, meat.utils.mixin.DictMixin),
        ),
        migrations.RemoveField(
            model_name='outstorage',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='outstorage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outstorage',
            name='user',
        ),
        migrations.DeleteModel(
            name='OutStorage',
        ),
    ]
