# Generated by Django 2.0 on 2018-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20180517_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
