# Generated by Django 2.0.5 on 2018-06-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20180528_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': (), 'permissions': (('product_list', '查看'), ('post_product', '编辑'), ('del_product', '删除'), ('enter_stat', '入库统计'), ('out_stat', '销售统计')), 'verbose_name': '产品'},
        ),
    ]
