# Generated by Django 2.0.5 on 2018-06-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20180602_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterstorage',
            options={'default_permissions': (), 'permissions': (('storage_enter', '入库'), ('enter_stat', '入库统计')), 'verbose_name': '入库'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': (), 'permissions': (('order', '查看订单'), ('order_edit', '创建订单'), ('delete_order', '删除订单'), ('out_stat', '销售统计')), 'verbose_name': '销售订单'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': (), 'permissions': (('product_list', '查看'), ('post_product', '编辑'), ('del_product', '删除')), 'verbose_name': '产品'},
        ),
    ]
