# Generated by Django 2.0.3 on 2018-06-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20180603_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageinfo',
            options={'default_permissions': (), 'permissions': (('storage_list', '盘库'),), 'verbose_name': '库存'},
        ),
    ]
