# Generated by Django 2.0.3 on 2018-06-04 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meat.utils.mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0014_auto_20180603_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('check_desc', models.CharField(max_length=50)),
                ('check_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, meat.utils.mixin.DictMixin),
        ),
    ]
