# Generated by Django 2.0.3 on 2018-06-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_loss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loss',
            options={'default_permissions': (), 'permissions': (('loss_list', '查看'),), 'verbose_name': '报损'},
        ),
    ]
