# Generated by Django 2.0.3 on 2018-06-06 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meat.utils.mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0016_auto_20180604_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('state', models.IntegerField(default=0)),
                ('opt_user', models.CharField(max_length=20)),
                ('check_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('check_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exch_check_user', to=settings.AUTH_USER_MODEL)),
                ('cusotmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Customer')),
            ],
            options={
                'verbose_name': '退换货',
                'permissions': (('exchange_list', '查看'),),
                'default_permissions': (),
            },
            bases=(models.Model, meat.utils.mixin.DictMixin),
        ),
        migrations.CreateModel(
            name='ExchangeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('direct', models.IntegerField(default=0)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Exchange')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Product')),
            ],
            options={
                'default_permissions': (),
            },
            bases=(models.Model, meat.utils.mixin.DictMixin),
        ),
    ]
