"""
    模块集合
"""

modules = [
        {
            "id": 1,
            "name": "收购",
            "url": "collect",
            "icon": "fa-tachometer",
            "label": "raw",
            "model": "collectinfo",
            "parent": 0,
            "children": [
                {
                    "name": "收购称重",
                    "url": "/raw/collect/create",
                    "icon": "fa-tachometer",
                    "label": "raw",
                    "model": "collectinfo",
                    "perimission": "collect_create",
                    "parent": 1,
                    "display": True,
                },
                {
                    "name": "收购台账",
                    "url": "/raw/collect/list",
                    "icon": "fa-table",
                    "label": "raw",
                    "model": "collectinfo",
                    "perimission": "collect_list",
                    "parent": 1,
                    "display": True,
                },
                {
                    "name": "收购品种管理",
                    "url": "/raw/category/list",
                    "icon": "fa-table",
                    "label": "raw",
                    "model": "Category",
                    "perimission": "category_list",
                    "parent": 1,
                    "display": True,
                },
                {
                    "name": "收购参数设置",
                    "url": "/raw/config",
                    "icon": "fa-table",
                    "label": "raw",
                    "model": "RawConfig",
                    "perimission": "config_edit",
                    "parent": 1,
                    "display": True,
                },
            ]
        },
        {
            "id": 2,
            "name": "加工",
            "icon": "fa-asterisk",
            "url": "production",
            "label": "raw",
            "model": "collectinfo",
            "parent": 0,
            "children": [
                {
                    "name": "排酸称重",
                    "url": "#",
                    "icon": "fa-table",
                    "label": "raw",
                    "model": "collectinfo",
                    "perimission": "",
                    "parent": 2,
                    "display": True,
                },
                {
                    "name": "排酸台账",
                    "url": "#",
                    "icon": "fa-table",
                    "label": "raw",
                    "model": "collectinfo",
                    "perimission": "",
                    "parent": 2,
                    "display": True,
                }
            ]
        },
        {
            "id": 3,
            "name": "库存",
            "icon": "fa-barcode",
            "url": "storage",
            "label": "storage",
            "model": "",
            "parent": 0,
            "children": [
                {
                    "name": "产品",
                    "url": "/storage/product/list",
                    "icon": "",
                    "label": "storage",
                    "model": "",
                    "perimission": "product_list",
                    "parent": 3,
                    "display": True,
                },
                {
                    "name": "入库",
                    "url": "/storage/enter",
                    "icon": "",
                    "label": "storage",
                    "model": "",
                    "perimission": "storage_enter",
                    "parent": 3,
                    "display": True,
                },
{
                    "name": "盘库",
                    "url": "/storage/info",
                    "icon": "",
                    "label": "storage",
                    "model": "",
                    "perimission": "storage_list",
                    "parent": 3,
                    "display": True,
                },
                {
                    "name": "出库记录",
                    "url": "/storage/order",
                    "icon": "",
                    "label": "storage",
                    "model": "",
                    "perimission": "order",
                    "parent": 3,
                    "display": True,
                }
            ],
        },
        {
            "id": 4,
            "name": "统计分析",
            "url": "stat",
            "icon": "fa-th",
            "parent": 0,
            "children": [
                {
                    "id": 401,
                    "name": "收购统计",
                    "url": "/raw/stat",
                    "label": "raw",
                    "model": "",
                    "perimission": "stat_list",
                    "parent": 5,
                    "display": True,
                },
                {
                    "id": 402,
                    "name": "收购分析",
                    "url": "/raw/analyze",
                    "label": "raw",
                    "model": "CollectInfo",
                    "perimission": "collect_analyze",
                    "parent": 5,
                    "display": True,
                },
                {
                    "id": 403,
                    "name": "入库统计",
                    "url": "/storage/enter/stat",
                    "label": "storage",
                    "model": "",
                    "perimission": "enter_stat",
                    "parent": 5,
                    "display": True,
                },
                {
                    "id": 404,
                    "name": "销售统计",
                    "url": "/storage/out/stat",
                    "label": "storage",
                    "model": "Order",
                    "perimission": "out_stat",
                    "parent": 5,
                    "display": True,
                },
{
                    "id": 405,
                    "name": "销售分析",
                    "url": "/storage/out/analysis",
                    "label": "storage",
                    "model": "",
                    "perimission": "order_analysis",
                    "parent": 5,
                    "display": True,
                }
            ]
        },
        {
            "id": 5,
            "name": "系统管理",
            "url": "system",
            "icon": "fa-user",
            "parent": 0,
            "children": [
                {
                    "id": 501,
                    "name": "用户管理",
                    "url": "/system/user",
                    "label": "",
                    "model": "",
                    "perimission": "",
                    "parent": 5,
                    "display": True,
                },
                {
                    "id": 502,
                    "name": "角色管理",
                    "url": "/system/role",
                    "label": "",
                    "model": "",
                    "perimission": "",
                    "parent": 5,
                    "display": True,
                }
            ]
        }
    ]