# Generated by Django 2.0 on 2018-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0002_auto_20180505_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(db_index=True, max_length=2)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='collectinfo',
            name='sg_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
