# Generated by Django 2.0 on 2018-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0004_auto_20180505_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectdetail',
            name='seq',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='collectinfo',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
