# Generated by Django 2.0 on 2018-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0005_auto_20180505_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinfo',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
