# Generated by Django 2.0 on 2018-05-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0006_payinfo_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('create_weight', '称重'), ('view_weight', '查看称重台账'), ('edit_weight', '编辑称重台账'), ('del_weight', '删除称重台账')),
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rawconfig',
            options={'permissions': (('view_rawconfig', '允许查看'),)},
        ),
    ]
