# Generated by Django 2.0 on 2018-05-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0007_auto_20180524_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
