# Generated by Django 2.0.5 on 2018-06-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0012_auto_20180602_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectinfo',
            options={'default_permissions': (), 'permissions': (('collect_list', '查看'), ('collect_create', '称重'), ('collect_edit', '编辑'), ('collect_delete', '删除'), ('collect_payview', '结算'), ('collect_print', '打印'), ('stat_list', '统计'), ('collect_analyze', '收购分析')), 'verbose_name': '收购'},
        ),
    ]
