# Generated by Django 2.0.3 on 2018-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0013_auto_20180602_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdetail',
            name='m_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='collectdetail',
            name='p_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='collectdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='collectdetail',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='collectinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='collectinfo',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='payinfo',
            name='pay_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
